name: kenyandictionaryapp
description: "A Flutter dictionary app."

publish_to: 'none'  # private project

version: 1.0.0+1

environment:
  sdk: '^3.9.0'   # Lower-bound fixed for package resolution

dependencies:
  flutter:
    sdk: flutter

  # Environment variables
  envied: ^0.5.4+1

  #caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Backend
  supabase_flutter: ^2.8.3
  http: ^1.2.1

  # State / storage
  shared_preferences: ^2.2.3

  # UI
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.3
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  envied_generator: ^0.5.4
  mocktail: ^1.0.4
  hive_generator: ^2.0.0
  

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - .env  # for Envied

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
